name: HoYoScript Schedule

on:
    schedule:
        - cron: "0 * * * *"
    push:
        branches: main

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v4
              with:
                  path: cache.json
                  key: ${{runner.os}}

            - name: Secret
              run: echo '${{secrets.DATA}}' > secret.json

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            - name: Run
              run: bun src/app.ts
